//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ShareSemanticInterfaces
{
    [Serializable]
    public class CanonicalBottleObservationMsg : Message
    {
        public const string k_RosMessageName = "share_semantic_interfaces/CanonicalBottleObservation";
        public override string RosMessageName => k_RosMessageName;

        //  Identity transport only. This message deliberately carries no pose and does
        //  not certify camera-to-Unity or camera-to-robot spatial authority.
        public const byte OBSERVED = 0;
        public const byte LOST = 1;
        public const byte REMOVED = 2;
        public string source_id;
        public string session_id;
        public ulong object_id;
        public byte lifecycle;
        public ulong observation_sequence;
        public BuiltinInterfaces.TimeMsg observation_stamp;
        public string observation_clock_domain;
        public string frame_id;

        public CanonicalBottleObservationMsg()
        {
            this.source_id = "";
            this.session_id = "";
            this.object_id = 0;
            this.lifecycle = 0;
            this.observation_sequence = 0;
            this.observation_stamp = new BuiltinInterfaces.TimeMsg();
            this.observation_clock_domain = "";
            this.frame_id = "";
        }

        public CanonicalBottleObservationMsg(string source_id, string session_id, ulong object_id, byte lifecycle, ulong observation_sequence, BuiltinInterfaces.TimeMsg observation_stamp, string observation_clock_domain, string frame_id)
        {
            this.source_id = source_id;
            this.session_id = session_id;
            this.object_id = object_id;
            this.lifecycle = lifecycle;
            this.observation_sequence = observation_sequence;
            this.observation_stamp = observation_stamp;
            this.observation_clock_domain = observation_clock_domain;
            this.frame_id = frame_id;
        }

        public static CanonicalBottleObservationMsg Deserialize(MessageDeserializer deserializer) => new CanonicalBottleObservationMsg(deserializer);

        private CanonicalBottleObservationMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.source_id);
            deserializer.Read(out this.session_id);
            deserializer.Read(out this.object_id);
            deserializer.Read(out this.lifecycle);
            deserializer.Read(out this.observation_sequence);
            this.observation_stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.observation_clock_domain);
            deserializer.Read(out this.frame_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.source_id);
            serializer.Write(this.session_id);
            serializer.Write(this.object_id);
            serializer.Write(this.lifecycle);
            serializer.Write(this.observation_sequence);
            serializer.Write(this.observation_stamp);
            serializer.Write(this.observation_clock_domain);
            serializer.Write(this.frame_id);
        }

        public override string ToString()
        {
            return "CanonicalBottleObservationMsg: " +
            "\nsource_id: " + source_id.ToString() +
            "\nsession_id: " + session_id.ToString() +
            "\nobject_id: " + object_id.ToString() +
            "\nlifecycle: " + lifecycle.ToString() +
            "\nobservation_sequence: " + observation_sequence.ToString() +
            "\nobservation_stamp: " + observation_stamp.ToString() +
            "\nobservation_clock_domain: " + observation_clock_domain.ToString() +
            "\nframe_id: " + frame_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
