//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ShareSemanticInterfaces
{
    [Serializable]
    public class LocalHoldStateMsg : Message
    {
        public const string k_RosMessageName = "share_semantic_interfaces/LocalHoldState";
        public override string RosMessageName => k_RosMessageName;

        //  Estimator-generated semantics, NOT physical ground truth or ownership.
        //  Identity uses SharedMRParticipantId names, not an invented numeric enum.
        public string participant_id;
        //  New UUID per publisher lifetime; receiver must explicitly bind a session.
        public string session_id;
        public ulong sequence;
        //  Nanoseconds in the source clock domain; never subtract another PC's clock.
        public bool source_timestamp_valid;
        public ulong source_timestamp_ns;
        public bool valid;
        public bool holds_object;
        public bool grasp_candidate_valid;
        public long grasp_candidate_object_id;
        public bool held_object_valid;
        public long held_object_id;
        public bool close_intent_valid;
        public bool close_intent;
        public bool intermediate_stop_valid;
        public bool intermediate_stop;
        public bool bottle_near_ee_valid;
        public bool bottle_near_ee;
        public bool load_detected_available;
        public bool load_detected_valid;
        public bool load_detected;
        public bool main_condition;
        public bool bottle_ee_distance_valid;
        public double bottle_ee_distance;
        public bool gripper_actual_position_valid;
        public double gripper_actual_position;
        public bool last_transition_time_valid;
        public ulong last_transition_time_ns;
        //  Research diagnostics; do not mirror these strings into Photon Networked State.
        public string invalid_reason;
        public string load_invalid_reason;
        //  Parallel arrays, same length, age may be negative for future-stamp failures.
        public string[] input_age_names;
        public bool[] input_age_valid;
        public long[] input_ages_ns;
        public string[] stale_inputs;

        public LocalHoldStateMsg()
        {
            this.participant_id = "";
            this.session_id = "";
            this.sequence = 0;
            this.source_timestamp_valid = false;
            this.source_timestamp_ns = 0;
            this.valid = false;
            this.holds_object = false;
            this.grasp_candidate_valid = false;
            this.grasp_candidate_object_id = 0;
            this.held_object_valid = false;
            this.held_object_id = 0;
            this.close_intent_valid = false;
            this.close_intent = false;
            this.intermediate_stop_valid = false;
            this.intermediate_stop = false;
            this.bottle_near_ee_valid = false;
            this.bottle_near_ee = false;
            this.load_detected_available = false;
            this.load_detected_valid = false;
            this.load_detected = false;
            this.main_condition = false;
            this.bottle_ee_distance_valid = false;
            this.bottle_ee_distance = 0.0;
            this.gripper_actual_position_valid = false;
            this.gripper_actual_position = 0.0;
            this.last_transition_time_valid = false;
            this.last_transition_time_ns = 0;
            this.invalid_reason = "";
            this.load_invalid_reason = "";
            this.input_age_names = new string[0];
            this.input_age_valid = new bool[0];
            this.input_ages_ns = new long[0];
            this.stale_inputs = new string[0];
        }

        public LocalHoldStateMsg(string participant_id, string session_id, ulong sequence, bool source_timestamp_valid, ulong source_timestamp_ns, bool valid, bool holds_object, bool grasp_candidate_valid, long grasp_candidate_object_id, bool held_object_valid, long held_object_id, bool close_intent_valid, bool close_intent, bool intermediate_stop_valid, bool intermediate_stop, bool bottle_near_ee_valid, bool bottle_near_ee, bool load_detected_available, bool load_detected_valid, bool load_detected, bool main_condition, bool bottle_ee_distance_valid, double bottle_ee_distance, bool gripper_actual_position_valid, double gripper_actual_position, bool last_transition_time_valid, ulong last_transition_time_ns, string invalid_reason, string load_invalid_reason, string[] input_age_names, bool[] input_age_valid, long[] input_ages_ns, string[] stale_inputs)
        {
            this.participant_id = participant_id;
            this.session_id = session_id;
            this.sequence = sequence;
            this.source_timestamp_valid = source_timestamp_valid;
            this.source_timestamp_ns = source_timestamp_ns;
            this.valid = valid;
            this.holds_object = holds_object;
            this.grasp_candidate_valid = grasp_candidate_valid;
            this.grasp_candidate_object_id = grasp_candidate_object_id;
            this.held_object_valid = held_object_valid;
            this.held_object_id = held_object_id;
            this.close_intent_valid = close_intent_valid;
            this.close_intent = close_intent;
            this.intermediate_stop_valid = intermediate_stop_valid;
            this.intermediate_stop = intermediate_stop;
            this.bottle_near_ee_valid = bottle_near_ee_valid;
            this.bottle_near_ee = bottle_near_ee;
            this.load_detected_available = load_detected_available;
            this.load_detected_valid = load_detected_valid;
            this.load_detected = load_detected;
            this.main_condition = main_condition;
            this.bottle_ee_distance_valid = bottle_ee_distance_valid;
            this.bottle_ee_distance = bottle_ee_distance;
            this.gripper_actual_position_valid = gripper_actual_position_valid;
            this.gripper_actual_position = gripper_actual_position;
            this.last_transition_time_valid = last_transition_time_valid;
            this.last_transition_time_ns = last_transition_time_ns;
            this.invalid_reason = invalid_reason;
            this.load_invalid_reason = load_invalid_reason;
            this.input_age_names = input_age_names;
            this.input_age_valid = input_age_valid;
            this.input_ages_ns = input_ages_ns;
            this.stale_inputs = stale_inputs;
        }

        public static LocalHoldStateMsg Deserialize(MessageDeserializer deserializer) => new LocalHoldStateMsg(deserializer);

        private LocalHoldStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.participant_id);
            deserializer.Read(out this.session_id);
            deserializer.Read(out this.sequence);
            deserializer.Read(out this.source_timestamp_valid);
            deserializer.Read(out this.source_timestamp_ns);
            deserializer.Read(out this.valid);
            deserializer.Read(out this.holds_object);
            deserializer.Read(out this.grasp_candidate_valid);
            deserializer.Read(out this.grasp_candidate_object_id);
            deserializer.Read(out this.held_object_valid);
            deserializer.Read(out this.held_object_id);
            deserializer.Read(out this.close_intent_valid);
            deserializer.Read(out this.close_intent);
            deserializer.Read(out this.intermediate_stop_valid);
            deserializer.Read(out this.intermediate_stop);
            deserializer.Read(out this.bottle_near_ee_valid);
            deserializer.Read(out this.bottle_near_ee);
            deserializer.Read(out this.load_detected_available);
            deserializer.Read(out this.load_detected_valid);
            deserializer.Read(out this.load_detected);
            deserializer.Read(out this.main_condition);
            deserializer.Read(out this.bottle_ee_distance_valid);
            deserializer.Read(out this.bottle_ee_distance);
            deserializer.Read(out this.gripper_actual_position_valid);
            deserializer.Read(out this.gripper_actual_position);
            deserializer.Read(out this.last_transition_time_valid);
            deserializer.Read(out this.last_transition_time_ns);
            deserializer.Read(out this.invalid_reason);
            deserializer.Read(out this.load_invalid_reason);
            deserializer.Read(out this.input_age_names, deserializer.ReadLength());
            deserializer.Read(out this.input_age_valid, sizeof(bool), deserializer.ReadLength());
            deserializer.Read(out this.input_ages_ns, sizeof(long), deserializer.ReadLength());
            deserializer.Read(out this.stale_inputs, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.participant_id);
            serializer.Write(this.session_id);
            serializer.Write(this.sequence);
            serializer.Write(this.source_timestamp_valid);
            serializer.Write(this.source_timestamp_ns);
            serializer.Write(this.valid);
            serializer.Write(this.holds_object);
            serializer.Write(this.grasp_candidate_valid);
            serializer.Write(this.grasp_candidate_object_id);
            serializer.Write(this.held_object_valid);
            serializer.Write(this.held_object_id);
            serializer.Write(this.close_intent_valid);
            serializer.Write(this.close_intent);
            serializer.Write(this.intermediate_stop_valid);
            serializer.Write(this.intermediate_stop);
            serializer.Write(this.bottle_near_ee_valid);
            serializer.Write(this.bottle_near_ee);
            serializer.Write(this.load_detected_available);
            serializer.Write(this.load_detected_valid);
            serializer.Write(this.load_detected);
            serializer.Write(this.main_condition);
            serializer.Write(this.bottle_ee_distance_valid);
            serializer.Write(this.bottle_ee_distance);
            serializer.Write(this.gripper_actual_position_valid);
            serializer.Write(this.gripper_actual_position);
            serializer.Write(this.last_transition_time_valid);
            serializer.Write(this.last_transition_time_ns);
            serializer.Write(this.invalid_reason);
            serializer.Write(this.load_invalid_reason);
            serializer.WriteLength(this.input_age_names);
            serializer.Write(this.input_age_names);
            serializer.WriteLength(this.input_age_valid);
            serializer.Write(this.input_age_valid);
            serializer.WriteLength(this.input_ages_ns);
            serializer.Write(this.input_ages_ns);
            serializer.WriteLength(this.stale_inputs);
            serializer.Write(this.stale_inputs);
        }

        public override string ToString()
        {
            return "LocalHoldStateMsg: " +
            "\nparticipant_id: " + participant_id.ToString() +
            "\nsession_id: " + session_id.ToString() +
            "\nsequence: " + sequence.ToString() +
            "\nsource_timestamp_valid: " + source_timestamp_valid.ToString() +
            "\nsource_timestamp_ns: " + source_timestamp_ns.ToString() +
            "\nvalid: " + valid.ToString() +
            "\nholds_object: " + holds_object.ToString() +
            "\ngrasp_candidate_valid: " + grasp_candidate_valid.ToString() +
            "\ngrasp_candidate_object_id: " + grasp_candidate_object_id.ToString() +
            "\nheld_object_valid: " + held_object_valid.ToString() +
            "\nheld_object_id: " + held_object_id.ToString() +
            "\nclose_intent_valid: " + close_intent_valid.ToString() +
            "\nclose_intent: " + close_intent.ToString() +
            "\nintermediate_stop_valid: " + intermediate_stop_valid.ToString() +
            "\nintermediate_stop: " + intermediate_stop.ToString() +
            "\nbottle_near_ee_valid: " + bottle_near_ee_valid.ToString() +
            "\nbottle_near_ee: " + bottle_near_ee.ToString() +
            "\nload_detected_available: " + load_detected_available.ToString() +
            "\nload_detected_valid: " + load_detected_valid.ToString() +
            "\nload_detected: " + load_detected.ToString() +
            "\nmain_condition: " + main_condition.ToString() +
            "\nbottle_ee_distance_valid: " + bottle_ee_distance_valid.ToString() +
            "\nbottle_ee_distance: " + bottle_ee_distance.ToString() +
            "\ngripper_actual_position_valid: " + gripper_actual_position_valid.ToString() +
            "\ngripper_actual_position: " + gripper_actual_position.ToString() +
            "\nlast_transition_time_valid: " + last_transition_time_valid.ToString() +
            "\nlast_transition_time_ns: " + last_transition_time_ns.ToString() +
            "\ninvalid_reason: " + invalid_reason.ToString() +
            "\nload_invalid_reason: " + load_invalid_reason.ToString() +
            "\ninput_age_names: " + System.String.Join(", ", input_age_names.ToList()) +
            "\ninput_age_valid: " + System.String.Join(", ", input_age_valid.ToList()) +
            "\ninput_ages_ns: " + System.String.Join(", ", input_ages_ns.ToList()) +
            "\nstale_inputs: " + System.String.Join(", ", stale_inputs.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
